# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: featureselector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='featureselector.proto',
  package='featureselector',
  syntax='proto3',
  serialized_pb=_b('\n\x15\x66\x65\x61tureselector.proto\x12\x0f\x66\x65\x61tureselector\"\xa9\x01\n\x0cnumericArray\x12\x38\n\ncovariates\x18\x01 \x03(\x0b\x32$.featureselector.numericArray.Column\x12\x36\n\x08response\x18\x02 \x01(\x0b\x32$.featureselector.numericArray.Column\x1a\'\n\x06\x43olumn\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x65ntries\x18\x02 \x03(\x02\"\x1e\n\nstringList\x12\x10\n\x08messages\x18\x01 \x03(\t2\\\n\x0f\x46\x65\x61tureSelector\x12I\n\tfsLassoCV\x12\x1d.featureselector.numericArray\x1a\x1b.featureselector.stringList\"\x00\x62\x06proto3')
)




_NUMERICARRAY_COLUMN = _descriptor.Descriptor(
  name='Column',
  full_name='featureselector.numericArray.Column',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='featureselector.numericArray.Column.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entries', full_name='featureselector.numericArray.Column.entries', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=212,
)

_NUMERICARRAY = _descriptor.Descriptor(
  name='numericArray',
  full_name='featureselector.numericArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='covariates', full_name='featureselector.numericArray.covariates', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response', full_name='featureselector.numericArray.response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NUMERICARRAY_COLUMN, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=212,
)


_STRINGLIST = _descriptor.Descriptor(
  name='stringList',
  full_name='featureselector.stringList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messages', full_name='featureselector.stringList.messages', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=244,
)

_NUMERICARRAY_COLUMN.containing_type = _NUMERICARRAY
_NUMERICARRAY.fields_by_name['covariates'].message_type = _NUMERICARRAY_COLUMN
_NUMERICARRAY.fields_by_name['response'].message_type = _NUMERICARRAY_COLUMN
DESCRIPTOR.message_types_by_name['numericArray'] = _NUMERICARRAY
DESCRIPTOR.message_types_by_name['stringList'] = _STRINGLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

numericArray = _reflection.GeneratedProtocolMessageType('numericArray', (_message.Message,), dict(

  Column = _reflection.GeneratedProtocolMessageType('Column', (_message.Message,), dict(
    DESCRIPTOR = _NUMERICARRAY_COLUMN,
    __module__ = 'featureselector_pb2'
    # @@protoc_insertion_point(class_scope:featureselector.numericArray.Column)
    ))
  ,
  DESCRIPTOR = _NUMERICARRAY,
  __module__ = 'featureselector_pb2'
  # @@protoc_insertion_point(class_scope:featureselector.numericArray)
  ))
_sym_db.RegisterMessage(numericArray)
_sym_db.RegisterMessage(numericArray.Column)

stringList = _reflection.GeneratedProtocolMessageType('stringList', (_message.Message,), dict(
  DESCRIPTOR = _STRINGLIST,
  __module__ = 'featureselector_pb2'
  # @@protoc_insertion_point(class_scope:featureselector.stringList)
  ))
_sym_db.RegisterMessage(stringList)



_FEATURESELECTOR = _descriptor.ServiceDescriptor(
  name='FeatureSelector',
  full_name='featureselector.FeatureSelector',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=246,
  serialized_end=338,
  methods=[
  _descriptor.MethodDescriptor(
    name='fsLassoCV',
    full_name='featureselector.FeatureSelector.fsLassoCV',
    index=0,
    containing_service=None,
    input_type=_NUMERICARRAY,
    output_type=_STRINGLIST,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FEATURESELECTOR)

DESCRIPTOR.services_by_name['FeatureSelector'] = _FEATURESELECTOR

# @@protoc_insertion_point(module_scope)
