package(default_visibility = ["//visibility:public"])

load("//bazel:grpc_build_system.bzl", "grpc_proto_library")

grpc_proto_library(
    name = "featureselector",
    srcs = ["protos/featureselector.proto"],
)
